import React, { useState } from 'react';
import { fmt, payLabels } from '../data';

const DailySummary = ({ data, clinicName }) => {
  const [copied, setCopied] = useState(false);
  const gapToTarget = data.target - data.mtd;
  const isAbove = gapToTarget <= 0;
  const totalPayments = Object.values(data.payments).reduce((a, b) => a + b, 0);

  const cardStyles = {
    app: { bg: 'bg-purple-50', border: 'border-purple-200', dot: 'bg-purple-500', text: 'text-purple-600' },
    nets: { bg: 'bg-blue-50', border: 'border-blue-200', dot: 'bg-blue-500', text: 'text-blue-600' },
    paynow: { bg: 'bg-emerald-50', border: 'border-emerald-200', dot: 'bg-emerald-500', text: 'text-emerald-600' },
    tpa: { bg: 'bg-amber-50', border: 'border-amber-200', dot: 'bg-amber-500', text: 'text-amber-600' },
    chas: { bg: 'bg-pink-50', border: 'border-pink-200', dot: 'bg-pink-500', text: 'text-pink-600' },
    healthiersg: { bg: 'bg-cyan-50', border: 'border-cyan-200', dot: 'bg-cyan-500', text: 'text-cyan-600' },
    cash: { bg: 'bg-green-50', border: 'border-green-200', dot: 'bg-green-500', text: 'text-green-600' },
    visa: { bg: 'bg-indigo-50', border: 'border-indigo-200', dot: 'bg-indigo-500', text: 'text-indigo-600' },
    mastercard: { bg: 'bg-orange-50', border: 'border-orange-200', dot: 'bg-orange-500', text: 'text-orange-600' },
    amex: { bg: 'bg-slate-50', border: 'border-slate-200', dot: 'bg-slate-500', text: 'text-slate-600' },
    copay: { bg: 'bg-rose-50', border: 'border-rose-200', dot: 'bg-rose-500', text: 'text-rose-600' },
  };

  const defaultStyle = { bg: 'bg-gray-50', border: 'border-gray-200', dot: 'bg-gray-500', text: 'text-gray-600' };
  const bgColors = ['bg-teal-50', 'bg-purple-50', 'bg-blue-50'];
  const txtColors = ['text-teal-600', 'text-purple-600', 'text-blue-600'];

  // WhatsApp summary data
  const avgWait = data.patients > 100 ? 12.0 : (data.patients > 50 ? 15.0 : 18.0);
  const throughput = data.patients > 100 ? 28.0 : (data.patients > 50 ? 31.5 : 35.0);
  const trialTarget = data.trial || Math.round(data.target * 1.15);
  const trialGap = Math.max(0, trialTarget - data.mtd);
  const services = [{ price: 60 }, { price: 45 }, { price: 280 }, { price: 180 }, { price: 25 }, { price: 90 }];
  const totalExtraServices = services.reduce((sum, s) => sum + Math.ceil(trialGap / s.price / services.length), 0);
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const dateStr = yesterday.toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).replace(/\//g, '/');
  const pctOfBase = ((data.mtd / data.target) * 100).toFixed(1);

  const whatsappText = `1doc MedOPs Daily Summary
📅 ${dateStr} | ${clinicName}

💰 Revenue
Today: S$${fmt(data.today)}
MTD: S$${fmt(data.mtd)}
MTD (Closing): S$${fmt(data.mtdFromClosing || data.mtd)}
👥 Patients: ${data.patients}
👨‍⚕️ Doctors: ${data.doctors.length}

💳 Payment Breakdown (MTD)
${Object.entries(data.payments).filter(([k, v]) => v > 0).sort((a, b) => b[1] - a[1]).map(([k, v]) => `• ${payLabels[k]}: S$${fmt(v)} (${((v / totalPayments) * 100).toFixed(1)}%)`).join('\n')}
Total: S$${fmt(totalPayments)}

⏱️ Topline KPI
Avg wait: ${avgWait.toFixed(1)} min
Throughput: ${throughput.toFixed(1)} min

🎯 Revenue Goal
Target: S$${fmt(data.target)} (${pctOfBase}% achieved)
Trial: S$${fmt(trialTarget)}
${data.mtd >= data.target ? '✅ Target exceeded!' : '→ S$' + fmt(data.target - data.mtd) + ' more to target'}
${trialGap > 0 ? '→ +' + totalExtraServices + ' extra services to trial' : '🎉 Trial target exceeded!'}

Auto-generated by 1doc MedOPs`;

  const copyWhatsAppSummary = () => {
    navigator.clipboard.writeText(whatsappText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="space-y-4">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded border border-gray-200 p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-teal-50 border border-teal-200 rounded flex items-center justify-center">
              <svg className="w-5 h-5 text-teal-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8V7m0 1v8m0 0v1" />
              </svg>
            </div>
            <span className="text-sm text-gray-500">MTD Revenue</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">S${fmt(data.mtd)}</p>
          <p className={`text-sm ${isAbove ? 'text-teal-600' : 'text-amber-600'} mt-1`}>
            {isAbove ? `+S$${fmt(Math.abs(gapToTarget))} above target` : `S$${fmt(gapToTarget)} to target`}
          </p>
        </div>

        <div className="bg-white rounded border border-gray-200 p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-purple-50 border border-purple-200 rounded flex items-center justify-center">
              <svg className="w-5 h-5 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
            </div>
            <span className="text-sm text-gray-500">Patients Yesterday</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">{data.patients}</p>
          <p className="text-sm text-purple-600 mt-1">{data.doctors.length} doctors on duty</p>
        </div>

        <div className="bg-white rounded border border-gray-200 p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-blue-50 border border-blue-200 rounded flex items-center justify-center">
              <svg className="w-5 h-5 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
            </div>
            <span className="text-sm text-gray-500">Today's Revenue</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">S${fmt(data.today)}</p>
          <p className="text-sm text-blue-600 mt-1">Daily target: S${fmt(data.daily)}</p>
        </div>

        <div className="bg-white rounded border border-gray-200 p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-emerald-50 border border-emerald-200 rounded flex items-center justify-center">
              <svg className="w-5 h-5 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <circle cx="12" cy="12" r="10" strokeWidth="2" />
                <circle cx="12" cy="12" r="6" strokeWidth="2" />
                <circle cx="12" cy="12" r="2" strokeWidth="2" />
              </svg>
            </div>
            <span className="text-sm text-gray-500">Target Progress</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">{((data.mtd / data.target) * 100).toFixed(1)}%</p>
          <div className="mt-2 bg-gray-200 rounded-full h-2">
            <div
              className="bg-teal-500 h-full rounded-full transition-all"
              style={{ width: `${Math.min((data.mtd / data.target) * 100, 100)}%` }}
            ></div>
          </div>
        </div>
      </div>

      {/* Doctor Performance */}
      <div className="bg-white rounded border border-gray-200 overflow-hidden">
        <div className="px-5 py-3 border-b border-gray-100 bg-gray-50">
          <h3 className="font-medium text-gray-800">Doctor Performance</h3>
        </div>
        <div className="p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {data.doctors.map((doc, i) => (
            <div key={i} className="flex items-center gap-3 p-3 bg-gray-50 rounded border border-gray-100">
              <div className={`w-10 h-10 ${bgColors[i % 3]} border border-gray-200 rounded flex items-center justify-center ${txtColors[i % 3]} font-bold text-sm`}>
                {doc.initials}
              </div>
              <div className="flex-1">
                <p className="font-medium text-gray-900 text-sm">{doc.name}</p>
                <p className="text-xs text-gray-500">{doc.patients} patients</p>
              </div>
              <div className="text-right">
                <p className="font-bold text-gray-900">S${fmt(doc.revenue)}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Payment Breakdown */}
      <div className="bg-white rounded border border-gray-200">
        <div className="px-5 py-3 border-b border-gray-100 bg-gray-50">
          <h3 className="font-medium text-gray-800">Payment Breakdown (MTD)</h3>
        </div>
        <div className="p-4">
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {Object.entries(data.payments)
              .filter(([k, v]) => v > 0)
              .sort((a, b) => b[1] - a[1])
              .map(([k, v]) => {
                const pct = ((v / totalPayments) * 100).toFixed(1);
                const style = cardStyles[k] || defaultStyle;
                return (
                  <div key={k} className={`${style.bg} ${style.border} border rounded p-4`}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className={`w-2 h-2 ${style.dot} rounded-full`}></span>
                      <span className={`text-sm font-medium ${style.text}`}>{payLabels[k] || k}</span>
                    </div>
                    <p className="text-lg font-bold text-gray-900">S${fmt(v)}</p>
                    <p className="text-xs text-gray-500 mt-1">{pct}% of total</p>
                  </div>
                );
              })}
          </div>
        </div>
      </div>

      {/* WhatsApp Auto-Summary */}
      <div className="bg-white rounded border border-gray-200 overflow-hidden">
        <div className="px-5 py-3 border-b border-gray-100 bg-gray-50 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-green-500 rounded flex items-center justify-center">
              <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 24 24">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
              </svg>
            </div>
            <div>
              <span className="font-medium text-gray-800">WhatsApp Auto-Summary</span>
              <p className="text-xs text-gray-500">Ready to copy & paste</p>
            </div>
          </div>
          <button
            onClick={copyWhatsAppSummary}
            className={`px-4 py-2 text-sm font-medium text-white rounded transition-colors ${copied ? 'bg-green-600' : 'bg-teal-600 hover:bg-teal-700'}`}
          >
            {copied ? 'Copied!' : 'Copy Message'}
          </button>
        </div>
        <div className="p-4">
          <div className="bg-gray-50 rounded border border-gray-200 p-4 text-sm text-gray-700 leading-relaxed whitespace-pre-wrap font-mono">
            <b>1doc MedOPs Daily Summary</b>
            {'\n'}📅 {dateStr} | {clinicName}
            {'\n\n'}💰 <b>Revenue</b>
            {'\n'}Today: S${fmt(data.today)}
            {'\n'}MTD: S${fmt(data.mtd)}
            {'\n'}MTD (Closing): S${fmt(data.mtdFromClosing || data.mtd)}
            {'\n'}👥 Patients: {data.patients}
            {'\n'}👨‍⚕️ Doctors: {data.doctors.length}
            {'\n\n'}💳 <b>Payment Breakdown (MTD)</b>
            {'\n'}{Object.entries(data.payments).filter(([k, v]) => v > 0).sort((a, b) => b[1] - a[1]).map(([k, v]) => `• ${payLabels[k]}: S$${fmt(v)} (${((v / totalPayments) * 100).toFixed(1)}%)`).join('\n')}
            {'\n'}Total: S${fmt(totalPayments)}
            {'\n\n'}⏱️ <b>Topline KPI</b>
            {'\n'}Avg wait: {avgWait.toFixed(1)} min
            {'\n'}Throughput: {throughput.toFixed(1)} min
            {'\n\n'}🎯 <b>Revenue Goal</b>
            {'\n'}Target: S${fmt(data.target)} ({pctOfBase}% achieved)
            {'\n'}Trial: S${fmt(trialTarget)}
            {'\n'}{data.mtd >= data.target ? '✅ Target exceeded!' : '→ S$' + fmt(data.target - data.mtd) + ' more to target'}
            {'\n'}{trialGap > 0 ? '→ +' + totalExtraServices + ' extra services to trial' : '🎉 Trial target exceeded!'}
            {'\n\n'}<span className="text-gray-400 italic">Auto-generated by 1doc MedOPs</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DailySummary;
